### PR TITLE
Allow generation of mandatory constraints

### PR DESCRIPTION
**Pull request by DamonOehlman**
As per #5 - @nathanoehlman would you mind taking a look, merging into master and publishing this to npm please.  I reckon a minor version bump is appropriate :)

### CODE REVIEW

**Comment by silviapfeiffer** [comment]
hmm are those tests supposed to return green?

**Comment by DamonOehlman** [comment]
Yep - they sure are.  I've asked travis to run them again (you can request a build be rescheduled easily) to see what the problem is.  From a cursory glance it looks like the implementation is ok, but something timed out somewhere...

**Comment by nathanoehlman** [comment]
@DamonOehlman Looks good to me! I'll merge it in and publish 2.2.0

**Comment by nathanoehlman** [comment]
@DamonOehlman Or rather I would publish a new version, but it seems that rtc-captureconfig is still owned only by you in NPM. If you can add me in as a collaborator, I'll publish away :)

**Comment by DamonOehlman** [comment]
@nathanoehlman no probs - will do.  How's the test status now?

**Comment by DamonOehlman** [comment]
done :)

**Comment by nathanoehlman** [comment]
Cheers :)

And tests are all in the green now - looks like it was just a time out issue before.

**Pull request merged**
